name: "Merge Gatekeeper"

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
      - master

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    name: merge-gatekeeper
    steps:
      - uses: funapy-sandbox/merge-gatekeeper@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
