name: merge-gatekeeper

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main

jobs:
  check-other-job-status:
    runs-on: ubuntu-latest
    name: merge-gatekeeper
    steps:
      - uses: funapy-sandbox/merge-gatekeeper@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
